[package]
name = "ownership_clone"
version = "0.1.0"
authors = ["charl"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
